// Copyright 2013 Szymon Sobczak: http://about.me/ssobczak
// Licensed under the MIT license: http://opensource.org/licenses/MIT
// The above copyright notice shall be included in all copies or substantial portions of the Software.

package gorosalind

import (
	"testing"
)

func TestMrna_example(t *testing.T) {
	protein := "MA"

	if mrna(protein, 1e6) != 12 {
		t.Error("Expected 12, got", mrna(protein, 1e6))
	}
}

func TestMrna_large(t *testing.T) {
	protein := "MHNMDENFSVIMTENHPMQFIDFFMFYKHKIQGDEATHKPWAFCLDQNLCRNDTQNFTHRYGWPQSGVCWNHSMLWKMFDSHHGAMWCLSLHQKLRIQDANTQMEEQTESDWAEFKQGGRLQDNSELSVSSNICLPFDVYPQFCLIVGGVKWMPTTSPSMAAYHFSDSTDRHFNETEEFWSFTADTPQLSLTFCVRVYMSITAQMQWRHLNCTARIAPLENGPEMLLKTAMLQFKVVAEWRDEYEYSNNCSQGLQMIGCEMIGLEESWNRGITHPNGKRFFTARPSATRYSERHIKPCARQMCSTDKYTAKPKKWRGVPVIAFETAQTTMDCTSGQDVFETTKQQKYQFHWPGMSEVRRLVQYVARRHMYKAGWMRWAPTMSCDTRSQPSQARNCAWHVGPGLVRIFNNKCPMHVYYDRWHGGNCICWDNHVCTMHHQRDSCRLGEPKPISTWRMKEDAKKQMSSFPRRTHRYGCWCWVKDIKQGISRHCFKNMKQAQHWDIYGNWVLMMYQAAEKMYWMDPEMLTNMAPTMHNALWIRLDTIDIPIFTNRAARRDATPYHFEYHCCTNEPYSYKFMDRCRDYFAAEIQQPAMPWKIVDPKNCWCFHWSNTTIVDNCLDAAMLWPRVTEPQRLNGIGNCWQVIVDWEGYKEEHEWFVIGQEWSWKACAFVKEPECNRIVWARLVTHYNFLGAGSLGMKHSLIYYSAEMSTDYYQNHGNVTALNCDSWAVVEWCRCIDDYFCWENDSIVHRHECEMMFNFGDIDQPYPHEYGAEPSAYKALKNGKSKPEETAVGPRCAFDKVIGWIYIKLYWSHLAHLHIHCDKDRDPKPKRWNQSNFDDCACDFCMMNLFGCDEFYMAHETHWAKFYNLQQKVETVWCARQQAQLVKCLALYSECRCMGFMNTKGIFVATCKGFGVHMNHMPKQRYFQDLMFGMLMVPTLRMGRALAQTGSAMIMWWDEAHQALKSMIVIEEGNHITPIKDPQHFNCNHSTVMYLWIPCM"

	if mrna(protein, 1e6) != 829632 {
		t.Error("Expected 829632, got", mrna(protein, 1e6))
	}
}
